### ISSUE TITLE
Não consigo rodar o seu projeto, pode ajudar ?

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [loiane/angular2-crud-auth-routing#4]
npm install
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/usr/share/npm/node_modules/which/which.js:78:19)
npm WARN addRemoteGit     at E (/usr/share/npm/node_modules/which/which.js:82:29)
npm WARN addRemoteGit     at /usr/share/npm/node_modules/which/which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  webpack/compression-webpack-plugin#7e55907cd54a2e91b96d25a660acc6a2a6453f54 resetting remote /root/.npm/_git-remotes/git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/webpack/compression-webpack-plugin.git /root/.npm/_git-remotes/git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/webpack/compression-webpack-plugin.git /root/.npm/_git-remotes/git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/usr/share/npm/node_modules/which/which.js:78:19)
npm WARN addRemoteGit     at E (/usr/share/npm/node_modules/which/which.js:82:29)
npm WARN addRemoteGit     at /usr/share/npm/node_modules/which/which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  webpack/compression-webpack-plugin#7e55907cd54a2e91b96d25a660acc6a2a6453f54 resetting remote /root/.npm/_git-remotes/git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/webpack/compression-webpack-plugin.git /root/.npm/_git-remotes/git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/webpack/compression-webpack-plugin.git /root/.npm/_git-remotes/git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/usr/share/npm/node_modules/which/which.js:78:19)
npm WARN addRemoteGit     at E (/usr/share/npm/node_modules/which/which.js:82:29)
npm WARN addRemoteGit     at /usr/share/npm/node_modules/which/which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  webpack/compression-webpack-plugin#7e55907cd54a2e91b96d25a660acc6a2a6453f54 resetting remote /root/.npm/_git-remotes/git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:webpack/compression-webpack-plugin.git /root/.npm/_git-remotes/git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:webpack/compression-webpack-plugin.git /root/.npm/_git-remotes/git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: undefined
npm ERR! Linux 4.8.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/angular2-crud-auth-routing/npm-debug.log
root@666:/var/www/html/angular2-crud-auth-routing#

**Comment by loiane** [comment]
Oi Junior, o erro está descrito na segunda linha: vc precisa instalar o git na sua máquina. []'s

**Comment by JoseRFJuniorLLMs** [comment]
npm -g install git
npm -g install github

Resolveria ?

**Comment by JoseRFJuniorLLMs** [comment]
Loiane Bom dia !
Para deixar registrado, resolvido assim : 

$ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash

$ nvm list
$ nvm ls-remote
$ nvm install 6.9.1
$ nvm use 6.9.1
$ nvm alias default 6.9.1
$ node -v
$ npm install -g npm
$ npm -v

sudo apt-get install git-all

Obrigado !

**Comment by JoseRFJuniorLLMs** [comment]
e isto aqui tbm:

delete node_modules
do a fresh npm i angular-cli@1.0.0-beta.18 -g
